spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/spring-security
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_commnets: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql